// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Data;

namespace Service.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211102093538_Fix")]
    partial class Fix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Authentication.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new { Id = "3375dc1e-b359-403e-9f13-5e2b395ffafc", AccessFailedCount = 0, ConcurrencyStamp = "8d38efea-1743-4521-b922-6cfc27fcea30", Email = "t.abdelmajid@Alexsys.solutions", EmailConfirmed = true, LockoutEnabled = false, NormalizedEmail = "T.ABDELMAJID@ALEXSYS.SOLUTIONS", NormalizedUserName = "ADMIN", PasswordHash = "AQAAAAEAACcQAAAAEK3afvPJrA7GC8vXZ1skkNcStydDeumR2BB0UWC+/lBe2J484rI9hkyP3SJn98s7vg==", PhoneNumberConfirmed = false, SecurityStamp = "78806f6d-7f1f-4d2f-9a13-ce06383ed217", TwoFactorEnabled = false, UserName = "admin" },
                        new { Id = "7167d11d-9358-4262-b7a4-77372e1c121d", AccessFailedCount = 0, ConcurrencyStamp = "dca68ed5-3781-43ad-9e82-dfa965ec284e", EmailConfirmed = false, LockoutEnabled = false, NormalizedUserName = "CHEFDEVENTE", PasswordHash = "AQAAAAEAACcQAAAAEGkYARWyxgAlpS4axLU7YUksdUCjY5RnW+rrIynUzwxxK97Bv2Zzc6lppqV1lGnGfQ==", PhoneNumberConfirmed = false, SecurityStamp = "45a41cea-397f-4837-9706-945073586524", TwoFactorEnabled = false, UserName = "chefdevente" },
                        new { Id = "2e142fe7-a372-4b98-ab9d-dcc4e4966b88", AccessFailedCount = 0, ConcurrencyStamp = "d3e54aa6-9687-40a5-b6f2-a1c55b59915f", EmailConfirmed = false, LockoutEnabled = false, NormalizedUserName = "RESPONSABLECOMMERCIAL", PasswordHash = "AQAAAAEAACcQAAAAECZ8DzIQ3GGyokJdu6sC9AwftKgSmurmPPt3NpzhD80I74EPcRudufgJuTMSOdkIKQ==", PhoneNumberConfirmed = false, SecurityStamp = "925b8781-e141-4f60-9dfc-293d3e24b78f", TwoFactorEnabled = false, UserName = "responsablecommercial" },
                        new { Id = "b8888a0f-ebcf-4b0a-815a-83ccc0a4c349", AccessFailedCount = 0, ConcurrencyStamp = "828d3b25-aff1-41e0-ae2e-e65cb3884199", EmailConfirmed = false, LockoutEnabled = false, NormalizedUserName = "DABPE", PasswordHash = "AQAAAAEAACcQAAAAEJg+9SYoyjUbN72cR8nd4/6W0x862uHiPeHWaLrfWm0t7XCUsEuF1rP0Sl6/Zr4yVg==", PhoneNumberConfirmed = false, SecurityStamp = "54227a7c-67ee-4ebb-b9d0-272ccb30e483", TwoFactorEnabled = false, UserName = "dabpe" },
                        new { Id = "3e45b10c-0d15-49f2-903b-7de4bbc62f98", AccessFailedCount = 0, ConcurrencyStamp = "d60dbadf-4597-44d7-990f-7f9af346a414", EmailConfirmed = false, LockoutEnabled = false, NormalizedUserName = "PRESCRIPTEURTECHNIQUE", PasswordHash = "AQAAAAEAACcQAAAAEM8VzG10a+2j/y+7Yij+maUogIOVsoCq6bwYa+wKSTcPbfXSSDUyjvHVx6dGvhyPyA==", PhoneNumberConfirmed = false, SecurityStamp = "58053aac-a438-4e44-acce-4f967d8df300", TwoFactorEnabled = false, UserName = "prescripteurtechnique" },
                        new { Id = "d19f9bc1-13b4-42b3-881a-a847f4c0684e", AccessFailedCount = 0, ConcurrencyStamp = "d163921a-d6ba-41eb-a925-602dfbad1e52", EmailConfirmed = false, LockoutEnabled = false, NormalizedUserName = "RESPONSABLELOGISTIQUE", PasswordHash = "AQAAAAEAACcQAAAAEGuEjF/ETf7BzTngq/VFjlj7Rn/WhGQPcF7H7r2jgygNxvclO3yo+SXGB0i2PUsjnQ==", PhoneNumberConfirmed = false, SecurityStamp = "adf0467d-bf4f-4bf5-a576-078dac83af6b", TwoFactorEnabled = false, UserName = "responsablelogistique" },
                        new { Id = "fe1300d0-ecf8-4bb5-afaf-5030b27959bd", AccessFailedCount = 0, ConcurrencyStamp = "9fb15432-698f-43b3-ac7f-e50bf0021bac", EmailConfirmed = false, LockoutEnabled = false, NormalizedUserName = "ADMINISTRATIONDESVENTES", PasswordHash = "AQAAAAEAACcQAAAAEKynR0WoYeYhJWUkKiWKTyexKYtKRk6GtmYF2x/zoPpQs5PWK41mNHO11Hf0EWjQtg==", PhoneNumberConfirmed = false, SecurityStamp = "02d7a2a5-9486-4980-b031-b1728f9125f1", TwoFactorEnabled = false, UserName = "administration des ventes" },
                        new { Id = "48e50810-f7fc-45c8-8d13-0a03a6a8b1de", AccessFailedCount = 0, ConcurrencyStamp = "62d6ff72-8268-4bd2-a469-36e61d929e46", EmailConfirmed = false, LockoutEnabled = false, NormalizedUserName = "CONTROLECREDIT", PasswordHash = "AQAAAAEAACcQAAAAEIZa6x+g2oj0her2UiADtyyosdh4ngrBj2BG5hr8I8JKirphPpfVZ3/vNPFJsI4MLg==", PhoneNumberConfirmed = false, SecurityStamp = "8e031d55-7c1e-4a55-896b-288a6f628ecd", TwoFactorEnabled = false, UserName = "controlecredit" }
                    );
                });

            modelBuilder.Entity("Domain.Entities.Article", b =>
                {
                    b.Property<int>("Article_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Tarif");

                    b.HasKey("Article_Id");

                    b.ToTable("Article");

                    b.HasData(
                        new { Article_Id = 1, Designation = "Beton 1", Tarif = 50.0 },
                        new { Article_Id = 2, Designation = "Beton 2", Tarif = 60.0 },
                        new { Article_Id = 3, Designation = "Beton 3", Tarif = 70.0 },
                        new { Article_Id = 4, Designation = "Beton Spécial" }
                    );
                });

            modelBuilder.Entity("Domain.Entities.CentraleBeton", b =>
                {
                    b.Property<int>("Ctr_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ctr_Adresse");

                    b.Property<int?>("Ctr_CodePostal");

                    b.Property<string>("Ctr_Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ctr_Gsm")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ctr_Latiture")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ctr_Longitude")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ctr_Nom")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ctr_Responsable")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ctr_Responsable_Gsm")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Ctr_Ville_Id");

                    b.Property<decimal?>("Rayon");

                    b.HasKey("Ctr_Id");

                    b.HasIndex("Ctr_Ville_Id");

                    b.ToTable("Centrale_Beton");

                    b.HasData(
                        new { Ctr_Id = 1, Ctr_Adresse = "Adresse 1", Ctr_CodePostal = 20250, Ctr_Email = "Centrale1@gmail.com", Ctr_Gsm = "0620055784", Ctr_Longitude = "-7.618710247586268", Ctr_Nom = "Centrale 1", Ctr_Responsable = "Test", Ctr_Responsable_Gsm = "0620055784", Ctr_Ville_Id = 2 },
                        new { Ctr_Id = 2, Ctr_Adresse = "Adresse 2", Ctr_CodePostal = 20250, Ctr_Email = "Centrale2@gmail.com", Ctr_Gsm = "0520055784", Ctr_Longitude = "-7.533456", Ctr_Nom = "Centrale 2", Ctr_Responsable = "Test 2", Ctr_Responsable_Gsm = "0625255784", Ctr_Ville_Id = 2 },
                        new { Ctr_Id = 3, Ctr_Adresse = "Adresse 3", Ctr_CodePostal = 20256, Ctr_Email = "Centrale3@gmail.com", Ctr_Gsm = "0525055784", Ctr_Longitude = "-7,6738", Ctr_Nom = "Centrale 3", Ctr_Responsable = "Test 3", Ctr_Responsable_Gsm = "0625285784", Ctr_Ville_Id = 2 }
                    );
                });

            modelBuilder.Entity("Domain.Entities.Chantier", b =>
                {
                    b.Property<int>("Ctn_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CentraleBetonCtr_Id");

                    b.Property<string>("Ctn_Adresse")
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Ctn_Ctr_Id");

                    b.Property<string>("Ctn_Latiture")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ctn_Longitude")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Ctn_Nom")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ctn_Tc_Id");

                    b.Property<int>("Ctn_Zone_Id");

                    b.Property<string>("Ctr_Nom");

                    b.Property<decimal>("Duree");

                    b.Property<string>("MaitreOuvrage");

                    b.Property<decimal>("Rayon");

                    b.Property<int?>("TypeChantierTc_Id");

                    b.Property<decimal>("VolumePrevisonnel");

                    b.HasKey("Ctn_Id");

                    b.HasIndex("CentraleBetonCtr_Id");

                    b.HasIndex("Ctn_Zone_Id");

                    b.HasIndex("TypeChantierTc_Id");

                    b.ToTable("Chantier");
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Property<int>("Client_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Client_Ctn_Id");

                    b.Property<string>("Cnie")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeClientSap")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Destinataire_Interlocuteur")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FormeJuridique_Id");

                    b.Property<string>("Gsm")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ice")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdPays");

                    b.Property<int>("IdVille");

                    b.Property<string>("RaisonSociale")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Client_Id");

                    b.HasIndex("Client_Ctn_Id");

                    b.HasIndex("FormeJuridique_Id");

                    b.HasIndex("IdPays");

                    b.HasIndex("IdVille");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Domain.Entities.Commande", b =>
                {
                    b.Property<int>("IdCommande")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeClientSap")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodeCommandeSap")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Conditions");

                    b.Property<string>("Currency");

                    b.Property<DateTime?>("DateCommande")
                        .HasColumnType("smalldatetime");

                    b.Property<DateTime?>("DateLivraisonSouhaite")
                        .HasColumnType("smalldatetime");

                    b.Property<int?>("DelaiPaiementDelai_Id");

                    b.Property<int>("Delai_Paiement_Id");

                    b.Property<int?>("IdClient");

                    b.Property<int?>("IdStatut");

                    b.Property<decimal?>("MontantCommande");

                    b.Property<double>("TarifPompage");

                    b.Property<double>("TarifTransport");

                    b.HasKey("IdCommande");

                    b.HasIndex("DelaiPaiementDelai_Id");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdStatut");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("Domain.Entities.DelaiPaiement", b =>
                {
                    b.Property<int>("Delai_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Delai_Libelle")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Delai_Id");

                    b.ToTable("Delai_Paiement");
                });

            modelBuilder.Entity("Domain.Entities.DetailCommande", b =>
                {
                    b.Property<int>("IdDetailCommande")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeArticleSap")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodeCommandeSap")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DateProduction");

                    b.Property<int?>("IdArticle");

                    b.Property<int?>("IdCommande");

                    b.Property<decimal?>("Montant");

                    b.Property<int?>("UniteIdUnite");

                    b.HasKey("IdDetailCommande");

                    b.HasIndex("IdArticle");

                    b.HasIndex("IdCommande");

                    b.HasIndex("UniteIdUnite");

                    b.ToTable("DetailCommande");
                });

            modelBuilder.Entity("Domain.Entities.FormeJuridique", b =>
                {
                    b.Property<int>("FormeJuridique_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FormeJuridique_Libelle")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("FormeJuridique_Id");

                    b.ToTable("Forme_Juridique");

                    b.HasData(
                        new { FormeJuridique_Id = 1, FormeJuridique_Libelle = "SA" },
                        new { FormeJuridique_Id = 2, FormeJuridique_Libelle = "SARL" }
                    );
                });

            modelBuilder.Entity("Domain.Entities.Paiement", b =>
                {
                    b.Property<int>("Paiement_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Conditions")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Paiement_Id");

                    b.ToTable("Paiement");
                });

            modelBuilder.Entity("Domain.Entities.Pays", b =>
                {
                    b.Property<int>("IdPays")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodePaysSap")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NomPays")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdPays");

                    b.ToTable("Pays");

                    b.HasData(
                        new { IdPays = 1, CodePaysSap = "MA", NomPays = "Maroc" }
                    );
                });

            modelBuilder.Entity("Domain.Entities.Statut", b =>
                {
                    b.Property<int>("IdStatut")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodeStatutSap")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStatut");

                    b.ToTable("Statut");

                    b.HasData(
                        new { IdStatut = 1, CodeStatutSap = "1", Libelle = "Etude et proposition de prix" },
                        new { IdStatut = 2, CodeStatutSap = "2", Libelle = "Parametrgage des prix PBE" },
                        new { IdStatut = 3, CodeStatutSap = "3", Libelle = "Validation de l'offre de prix" },
                        new { IdStatut = 4, CodeStatutSap = "4", Libelle = "Fixation de prix du transport" },
                        new { IdStatut = 5, CodeStatutSap = "5", Libelle = "Parametrgage des prix de services" },
                        new { IdStatut = 6, CodeStatutSap = "6", Libelle = "Validé" }
                    );
                });

            modelBuilder.Entity("Domain.Entities.TarifBetonRef", b =>
                {
                    b.Property<int>("Tbr_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Designation_Beton");

                    b.Property<double>("Tarif");

                    b.HasKey("Tbr_Id");

                    b.ToTable("Tarif_Ref");
                });

            modelBuilder.Entity("Domain.Entities.TarifPompeRef", b =>
                {
                    b.Property<int>("Tpr_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LongFleche_Libelle");

                    b.Property<decimal>("LongFleche_Prix");

                    b.HasKey("Tpr_Id");

                    b.ToTable("Tarif_Pompe");

                    b.HasData(
                        new { Tpr_Id = 1, LongFleche_Libelle = "48", LongFleche_Prix = 50m },
                        new { Tpr_Id = 2, LongFleche_Libelle = "50", LongFleche_Prix = 60m },
                        new { Tpr_Id = 3, LongFleche_Libelle = "52", LongFleche_Prix = 70m }
                    );
                });

            modelBuilder.Entity("Domain.Entities.TarifService", b =>
                {
                    b.Property<int>("TS_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("TarifPompage");

                    b.Property<double>("TarifTransport");

                    b.HasKey("TS_Id");

                    b.ToTable("Tarif_Service");
                });

            modelBuilder.Entity("Domain.Entities.TypeChantier", b =>
                {
                    b.Property<int>("Tc_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tc_Libelle")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Tc_Id");

                    b.ToTable("Type_Chantier");

                    b.HasData(
                        new { Tc_Id = 1, Tc_Libelle = "Type 1" },
                        new { Tc_Id = 2, Tc_Libelle = "Type 2" },
                        new { Tc_Id = 3, Tc_Libelle = "Type 3" }
                    );
                });

            modelBuilder.Entity("Domain.Entities.Unite", b =>
                {
                    b.Property<int>("IdUnite")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUnite");

                    b.ToTable("Unite");

                    b.HasData(
                        new { IdUnite = 1, Libelle = "m3" }
                    );
                });

            modelBuilder.Entity("Domain.Entities.Ville", b =>
                {
                    b.Property<int>("IdVille")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodePaysSap");

                    b.Property<string>("CodeVilleSap")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdPays");

                    b.Property<string>("NomVille")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdVille");

                    b.HasIndex("IdPays");

                    b.ToTable("Ville");

                    b.HasData(
                        new { IdVille = 1, CodePaysSap = "MA", CodeVilleSap = "R", IdPays = 1, NomVille = "Rabat" },
                        new { IdVille = 2, CodePaysSap = "MA", CodeVilleSap = "C", IdPays = 1, NomVille = "Casablanca" }
                    );
                });

            modelBuilder.Entity("Domain.Entities.Zone", b =>
                {
                    b.Property<int>("Zone_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Zone_Libelle")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Zone_Prix");

                    b.HasKey("Zone_Id");

                    b.ToTable("Zone");

                    b.HasData(
                        new { Zone_Id = 1, Zone_Libelle = "Zone 1", Zone_Prix = 50m },
                        new { Zone_Id = 2, Zone_Libelle = "Zone 2", Zone_Prix = 60m },
                        new { Zone_Id = 3, Zone_Libelle = "Zone 3", Zone_Prix = 70m }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new { Id = "48e33a01-bd1f-4739-a27f-126e8e8b2d1c", ConcurrencyStamp = "babf6afe-6eeb-47ee-aa48-748ff73e9aa3", Name = "Admin", NormalizedName = "ADMIN" },
                        new { Id = "1588b3b9-37bc-4f58-acf9-e42fd47f1c28", ConcurrencyStamp = "a43a78bd-3054-4fb8-98eb-83ebdda5d13e", Name = "Chef de ventes", NormalizedName = "CHEF DE VENTES" },
                        new { Id = "6eafdfbe-ed07-4687-9d2c-0b767b15a305", ConcurrencyStamp = "4b1336b9-8f33-4e82-8d61-fd3964922d73", Name = "Responsable commercial", NormalizedName = "RESPONSABLE COMMERCIAL" },
                        new { Id = "9be024db-d122-4cd2-8329-2afd0d259e77", ConcurrencyStamp = "6cc72c9f-281c-4ee7-a6dd-776c74110356", Name = "DA BPE", NormalizedName = "DA BPE" },
                        new { Id = "126a635b-d763-48bf-ab0e-f5599cffb4fe", ConcurrencyStamp = "b985ee2a-7a8c-4184-94aa-fff30148f79d", Name = "Prescripteur technique", NormalizedName = "PRESCRIPTEUR TECHNIQUE" },
                        new { Id = "a7846740-cb77-4d25-8da6-d5c68dfb590d", ConcurrencyStamp = "8bb223ab-33fd-45b2-a3e0-58887f4d3ef2", Name = "Responsable logistique", NormalizedName = "RESPONSABLE LOGISTIQUE" },
                        new { Id = "3e130fc1-981e-4183-a12d-fa5f73d13bb2", ConcurrencyStamp = "eeeb4552-2567-4c4b-aad5-ec43dc1ea4dd", Name = "Administration des ventes", NormalizedName = "ADMINISTRATION DES VENTES" },
                        new { Id = "7b8ab704-463e-4074-8c19-a62905f62e11", ConcurrencyStamp = "c328c361-882f-4b4f-b3bc-49fee26bc301", Name = "Controle crédit", NormalizedName = "CONTROLE CREDIT" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new { UserId = "3375dc1e-b359-403e-9f13-5e2b395ffafc", RoleId = "48e33a01-bd1f-4739-a27f-126e8e8b2d1c" },
                        new { UserId = "7167d11d-9358-4262-b7a4-77372e1c121d", RoleId = "1588b3b9-37bc-4f58-acf9-e42fd47f1c28" },
                        new { UserId = "2e142fe7-a372-4b98-ab9d-dcc4e4966b88", RoleId = "6eafdfbe-ed07-4687-9d2c-0b767b15a305" },
                        new { UserId = "b8888a0f-ebcf-4b0a-815a-83ccc0a4c349", RoleId = "9be024db-d122-4cd2-8329-2afd0d259e77" },
                        new { UserId = "3e45b10c-0d15-49f2-903b-7de4bbc62f98", RoleId = "126a635b-d763-48bf-ab0e-f5599cffb4fe" },
                        new { UserId = "d19f9bc1-13b4-42b3-881a-a847f4c0684e", RoleId = "a7846740-cb77-4d25-8da6-d5c68dfb590d" },
                        new { UserId = "fe1300d0-ecf8-4bb5-afaf-5030b27959bd", RoleId = "3e130fc1-981e-4183-a12d-fa5f73d13bb2" },
                        new { UserId = "48e50810-f7fc-45c8-8d13-0a03a6a8b1de", RoleId = "7b8ab704-463e-4074-8c19-a62905f62e11" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Domain.Entities.CentraleBeton", b =>
                {
                    b.HasOne("Domain.Entities.Ville", "VILLE")
                        .WithMany()
                        .HasForeignKey("Ctr_Ville_Id");
                });

            modelBuilder.Entity("Domain.Entities.Chantier", b =>
                {
                    b.HasOne("Domain.Entities.CentraleBeton", "CentraleBeton")
                        .WithMany()
                        .HasForeignKey("CentraleBetonCtr_Id");

                    b.HasOne("Domain.Entities.Zone", "ZONE_CHANTIER")
                        .WithMany()
                        .HasForeignKey("Ctn_Zone_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.TypeChantier", "TypeChantier")
                        .WithMany()
                        .HasForeignKey("TypeChantierTc_Id");
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.HasOne("Domain.Entities.Chantier", "Chantier")
                        .WithMany()
                        .HasForeignKey("Client_Ctn_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.FormeJuridique", "FormeJuridique")
                        .WithMany()
                        .HasForeignKey("FormeJuridique_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Pays", "Pays")
                        .WithMany()
                        .HasForeignKey("IdPays")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Entities.Ville", "Ville")
                        .WithMany()
                        .HasForeignKey("IdVille")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Domain.Entities.Commande", b =>
                {
                    b.HasOne("Domain.Entities.DelaiPaiement", "DelaiPaiement")
                        .WithMany()
                        .HasForeignKey("DelaiPaiementDelai_Id");

                    b.HasOne("Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("IdClient");

                    b.HasOne("Domain.Entities.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("IdStatut");
                });

            modelBuilder.Entity("Domain.Entities.DetailCommande", b =>
                {
                    b.HasOne("Domain.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("IdArticle");

                    b.HasOne("Domain.Entities.Commande", "Commande")
                        .WithMany("DetailCommandes")
                        .HasForeignKey("IdCommande");

                    b.HasOne("Domain.Entities.Unite", "Unite")
                        .WithMany()
                        .HasForeignKey("UniteIdUnite");
                });

            modelBuilder.Entity("Domain.Entities.Ville", b =>
                {
                    b.HasOne("Domain.Entities.Pays", "Pays")
                        .WithMany()
                        .HasForeignKey("IdPays");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Authentication.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Authentication.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Authentication.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Authentication.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
